#!/bin/sh


# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done

#/sbin/ifconfig eth0 192.168.17.101
#echo "nameserver 192.168.17.1" > /etc/resolv.conf
#/sbin/ip route add default via 192.168.17.1

#####################################################################################################################
#I/O EXPANDER
#
#
#I/O expander I2c bus:                         2
#I/O expander address:                         0x20
#I/O expander output register address:         0x01
#I/O expander configuration regiser address:   0x03
#
#I/Os list:
#
# IO0 -> SYSGD,   I/O Expander Input
# IO1 -> PFO#,    I/O Expander Input
# IO2 -> CAPGD,   I/O Expander Input
# IO3 -> CAPFLT#, I/O Expander Input
# IO4 -> CHGEN#,  I/O Expander Output, Value: 0
# IO5 -> BSTEN#,  I/O Expander Output, Value: 0
# IO6 -> N/C
# IO7 -> N/C
#
#Step 1: set output values (before configurating I/Os as output)
#
#configurate I/O Expander output values:
# 0000 0000 => 0x00
#
i2cset -y 2 0x20 0x01  0x00 -f
#
#
#Step 2: configurate I/O Expander inputs/outputs
#
#value: 0000 1111  =>  0x0f
i2cset -y 2 0x20 0x03 0x0f -f
#
#
#####################################################################################################################
# Enable the LTE Modem
## RF_PWR
pin=89
echo $pin > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio${pin}/direction
echo 1 > /sys/class/gpio/gpio${pin}/value

# LTE_PWR
pin=132
echo $pin > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio${pin}/direction
echo 1 > /sys/class/gpio/gpio${pin}/value

# LTE_PWR_PWERKEY
pin=7
echo $pin > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio${pin}/direction
echo 1 > /sys/class/gpio/gpio${pin}/value

# LTE RESET_n
pin=8
echo $pin > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio${pin}/direction
echo 1 > /sys/class/gpio/gpio${pin}/value

# HUB_RST
pin=131
echo $pin > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio${pin}/direction
echo 1 > /sys/class/gpio/gpio${pin}/value
#####################################################################################################################
